package com.fitness.fitnesstracker.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity representing a registered user in the system.
 * Mapped to the "users" table in the database.
 */
@Data
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier of the user, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The email address of the user.
     * Must be unique and cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The hashed password of the user.
     * Stored as a BCrypt hash, never as plain text.
     */
    @Column(nullable = false)
    private String password;

    /**
     * The first name of the user.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String firstName;

    /**
     * The last name of the user.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String lastName;

    /**
     * The role of the user in the system (USER or ADMIN).
     * Stored as a string value in the database.
     */
    @Enumerated(EnumType.STRING)
    private Role role;
}