package com.fitness.fitnesstracker.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity representing a user's fitness profile.
 * Mapped to the "user_profiles" table in the database.
 * Has a one-to-one relationship with the User entity.
 */
@Data
@Entity
@Table(name = "user_profiles")
public class UserProfile {

    /**
     * Unique identifier of the profile, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user this profile belongs to.
     * One-to-one relationship with the User entity.
     */
    @OneToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The age of the user in years.
     */
    private Integer age;

    /**
     * The height of the user in centimeters.
     */
    private Double height;

    /**
     * The weight of the user in kilograms.
     */
    private Double weight;

    /**
     * The fitness goal of the user (e.g. MUSCLE_GAIN, WEIGHT_LOSS).
     * Stored as a string value in the database.
     */
    @Enumerated(EnumType.STRING)
    private FitnessGoal goal;

    /**
     * The experience level of the user (e.g. BEGINNER, INTERMEDIATE, ADVANCED).
     * Stored as a string value in the database.
     */
    @Enumerated(EnumType.STRING)
    private ExperienceLevel experienceLevel;

    /**
     * The available equipment for the user (e.g. GYM, HOME, NO_EQUIPMENT).
     * Stored as a string value in the database.
     */
    @Enumerated(EnumType.STRING)
    private Equipment equipment;

    /**
     * Optional field describing any injuries or physical limitations of the user.
     * Used by the AI to avoid exercises that could worsen the condition.
     */
    private String injuries;
}