package com.fitness.fitnesstracker.model;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDate;

/**
 * Entity representing a user's workout progress entry.
 * Mapped to the "workout_progress" table in the database.
 */
@Data
@Entity
@Table(name = "workout_progress")
public class WorkoutProgress {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user this progress entry belongs to.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The current weight of the user at the time of entry.
     */
    private Double weight;

    /**
     * User notes about the workout session.
     */
    @Column(columnDefinition = "TEXT")
    private String notes;

    /**
     * Date when the progress was logged.
     */
    private LocalDate date;
}