package com.fitness.fitnesstracker.model;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * Entity representing an AI-generated workout plan for a user.
 * Mapped to the "workout_plans" table in the database.
 */
@Data
@Entity
@Table(name = "workout_plans")
public class WorkoutPlan {

    /**
     * Unique identifier of the workout plan, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user this workout plan belongs to.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The AI-generated workout plan content stored as text.
     */
    @Column(columnDefinition = "TEXT")
    private String content;

    /**
     * The date and time when the workout plan was generated.
     */
    private LocalDateTime createdAt;
}